version: "3.7"

services:

  cronjob:
    build: 
      context: .
      dockerfile: Dockerfile
    image: eqe-lab/cronjob
    container_name: cronjob
    restart: unless-stopped
    volumes:
      - ${CRON_BASE_DIR:-./cron}/scripts:/cron_scripts:ro
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      DEBUG: ${DEBUG:-"false"}
      LOCAL_EXEC: true

